name: Build and Publish Docker images
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set version variable
        run: |
          TAG=${{ github.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Setup docker
        uses: docker/setup-buildx-action@v2

      - name: Login container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        id: image-tags
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ids-basecamp/connector
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            ${{ github.ref_name }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.image-tags.outputs.tags }}
          labels: ${{ steps.image-tags.outputs.labels }}
          platforms: linux/amd64,linux/arm64
